
INSERT INTO DONVITINH VALUES(NULL, "Lô");
INSERT INTO DONVITINH VALUES(NULL, "Dây chuyền");
INSERT INTO DONVITINH VALUES(NULL, "Viên");
INSERT INTO DONVITINH VALUES(NULL, "kara");
INSERT INTO DONVITINH VALUES(NULL, "Hộp");
INSERT INTO DONVITINH VALUES(NULL, "Chiếc");


INSERT INTO LOAISANPHAM VALUES(NULL, "Dây chuyền", 2, 20);
INSERT INTO LOAISANPHAM VALUES(NULL, "Kim cương", 4, 15);
INSERT INTO LOAISANPHAM VALUES(NULL, "Vòng tay", 6, 10);
INSERT INTO LOAISANPHAM VALUES(NULL, "Vòng chân", 6, 7);
INSERT INTO LOAISANPHAM VALUES(NULL, "Nhẫn", 6, 25);






